apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: kong-backend-config
spec:
  cdn: 
    enabled: true
    
  healthCheck:
    checkIntervalSec: 15
    port: 8100
    requestPath: /status